experiment:
    id: fasterrcnn_leaves
    seed: 1324

checkpoint: 'checkpoints'
tensorboard: 'tensorboard'

##Training
train:
    n_gpus: 1
    workers: 10 
    max_epoch: 200
    batch_size: 12
    n_classes: 3
    overfit: False
    lr: 0.0001

val:
    nms_th: 0.5
    prob_th: 0.6


